### ISSUE TITLE
Question about backend regex engine used in CredSweeper

### ISSUE THREAD

**Issue by numairmansur** [Samsung/CredSweeper#435]
Hi, 

I have a question regarding the backend regex engine used in CredSweeper. 
My understanding is that at the backend, `re` is used. But is this true?

If I run the following rule, 
```
- name: some name
  severity: high
  type: pattern
  values:
    - (.*+)
  filter_type: GeneralPattern
  use_ml: false
  validations: []
  min_line_len: 1
  message: "some message..."
```

I get
```
2023-10-04 14:39:16,557 | INFO | __main__:276 | Run analyzer on path: ['secret.txt']
2023-10-04 14:39:16,623 | INFO | app:169 | Start Scanner
2023-10-04 14:39:16,623 | DEBUG | app:241 | Start scan file: secret.txt 
2023-10-04 14:39:16,623 | DEBUG | scan_type:95 | Valid line for pattern: regex.Regex('(.*+)', flags=regex.V0) in file: secret.txt:1 in line: .
2023-10-04 14:39:16,623 | DEBUG | scan_type:61 | Filtered line with filter: ValuePatternCheck in file: secret.txt:1  in line: .
20
```
From the logs it seems like the `regex` module is used instead of `re`.

**Comment by babenek** [comment]
Hello @numairmansur ,
please, specify your version of CredSweeper. ``--version`` 
It looks like obsolete code.

**Comment by babenek** [comment]
https://github.com/Samsung/CredSweeper/blob/d3bdb380334bfdbe87dbf4e6d86f012b0be97c9f/credsweeper/scanner/scan_type/scan_type.py#L95 - the line has no logger

**Comment by csh519** [comment]
Hello.
Actually we decided to use rather `re`  than `regex` on June. #350

**Comment by numairmansur** [comment]
I am using version `1.4.10`
```
python -m credsweeper --version
CredSweeper 1.4.10
```

**Comment by numairmansur** [comment]
I see so on `1.4.10` we were still using `regex` and now we have switched to `re`?

**Comment by numairmansur** [comment]
Got it! Thanks so much!
Just out of curiosity: Why did you guys decide to switch to `re`? Overall it seems like `regex` offers more features compared to `re`.

**Comment by babenek** [comment]
Main disadvantage was sometime vulnerabilities in ``regex`` that requires urgent fix and so on.
Performance still the same and all necessary features were migrated to standard ``re`` (python3.8 - the minimal supported version)
So, the necessary of using ``regex`` has vanished, that why we have migrated to standard ``re``.

**Comment by numairmansur** [comment]
Got it. 
But I think there are still some features not supported in `re`. For example, variable-length lookbehind assertions. 

```
>>> import re
>>> pattern = re.compile(r'(?<=a{2,4})b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 747, in compile
    code = _code(p, flags)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 580, in _code
    _compile(code, p.data, flags)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 153, in _compile
    raise error("look-behind requires fixed-width pattern")
re.error: look-behind requires fixed-width pattern
>>> 
>>> 
>>> 
>>> import regex
>>> pattern = regex.compile(r'(?<=a{2,4})b')
>>> match = pattern.search('aaab')
>>> bool(match)
True
```

**Comment by babenek** [comment]
@numairmansur 
Could you share a rule in which you apply the feature of regex and does not supported with current version of CredSweeper?
Finds the rule a real credential or it is just for academic investigation?
You can even do a pull request. Let it fails in regex compilation - we will try to fix it together.

**Comment by numairmansur** [comment]
@babenek Yup this is only for academic investigation. I will circle back with a CredSweeper rule that maybe uses variable-length lookbehind assertions to find a credential! Thank you. I can close this issue for now and will re-open it when I have it.
